### PR TITLE
pState: use pState from argument

### PR DESCRIPTION
**Pull request by charansai612**
pState is set to zeros internally even when pState is a non zero array

### CODE REVIEW

**Comment by christophe0606** [comment]
@charansai612 It is normal for the init function to reset the state to 0. It is in fact their main function : setting the filter into a known state.

If you need to set the state to another value, you may do it after the init. But why would it be needed ? Goertzel algorithm using a biquad ?

Note also that it won't be portable : the state encoding may be different depending on the core you target (vectorized filter etc ...). So if you rely on what is in the state for your own code, it may break if you move the algorithm to another target.

The state should only be used by the filter.

**Comment by charansai612** [comment]
I just implemented the python like sosfiltfilt using the arm_biquad_cascade function and found out the pState is set to zero, I  generated pState from the scipy in order to avoid the boundary effect.

Ya updating the state after init should also work.
Thank you

**Comment by christophe0606** [comment]
Thank you. I have created a github issue for a future enhancement:
https://github.com/ARM-software/CMSIS-DSP/issues/83

**Comment by Lukwrt** [comment]
@charansai612 I am also trying to replicate sosfiltfilt from Scipy (see [sosfiltfilt code source](https://github.com/scipy/scipy/blob/v1.13.0/scipy/signal/_signaltools.py#L4357-L4467)). However I don't get how to convert valuesfrom sosfiltzi to pstate argument of arm_biquad_cascade_df1_init_f32.

Let's say my zi computed via Scipy are : 
[[1 , 2]
  [3 , 4]]

How do I convert it to proper pStates for the biquad function ?
I tried to assign to pState "like this" : pState = {1, 2, 3, 4} but the result is not the same as I get in Scipy.

Should I post this comment in https://github.com/ARM-software/CMSIS-DSP/issues/83 ? As my comment is very closely related to this possible enhancement.

**Comment by Lukwrt** [comment]
I'm sorry for my previous comment. I was using the biquad cascade direct form 1 from CMSIS-DSP to implement Scipy sosfiltfilt but it was a mistake as this scipy function uses a direct form 2 structure. So switching to the biquad cascade direct form 2 in CMSIS works perfectly. I also have to compute the initial condition via sosfiltzi in Scipy but it is not a problem.

**Pull request closed without merging**
